// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC68yXHqqUTiF8ntdi_vPzpdFCBOMtD--Q',
    appId: '1:377762176742:web:0939baceeecd5b4e786527',
    messagingSenderId: '377762176742',
    projectId: 'moapp-toto',
    authDomain: 'moapp-toto.firebaseapp.com',
    storageBucket: 'moapp-toto.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOhFSh2aifG2pblN9rihfK8Atrh3Eh2N0',
    appId: '1:377762176742:android:5304c8ec1f97e2a7786527',
    messagingSenderId: '377762176742',
    projectId: 'moapp-toto',
    storageBucket: 'moapp-toto.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoenUSk8IB7mvjMiHXLLbryY8c-oEBh78',
    appId: '1:377762176742:ios:59bd45ff97dbb7a2786527',
    messagingSenderId: '377762176742',
    projectId: 'moapp-toto',
    storageBucket: 'moapp-toto.firebasestorage.app',
    iosClientId: '377762176742-6smdkhnnkc4ckrkv2ng71ifahsgphf2f.apps.googleusercontent.com',
    iosBundleId: 'com.example.moappToto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoenUSk8IB7mvjMiHXLLbryY8c-oEBh78',
    appId: '1:377762176742:ios:59bd45ff97dbb7a2786527',
    messagingSenderId: '377762176742',
    projectId: 'moapp-toto',
    storageBucket: 'moapp-toto.firebasestorage.app',
    iosClientId: '377762176742-6smdkhnnkc4ckrkv2ng71ifahsgphf2f.apps.googleusercontent.com',
    iosBundleId: 'com.example.moappToto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC68yXHqqUTiF8ntdi_vPzpdFCBOMtD--Q',
    appId: '1:377762176742:web:d86ab670c733984f786527',
    messagingSenderId: '377762176742',
    projectId: 'moapp-toto',
    authDomain: 'moapp-toto.firebaseapp.com',
    storageBucket: 'moapp-toto.firebasestorage.app',
  );

}